language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis ci 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - email
    on_success: never # default: change
    on_failure: always # default: always

before_deploy:
  - zip -r taglog * #파일 압축
  - mkdir -p deploy #travis가 설치된 위치에 배포 디렉토리 생성
  - mv taglog.zip deploy/taglog.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis에 저장한 키 변수 사용
    secret_access_key: $AWS_SECRET_KEY #Travis에 저장한 키 변수 사용
    bucket: taglog-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리. 여기에 있는 파일만 s3로 전송
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis에 저장한 키 변수 사용
    secret_access_key: $AWS_SECRET_KEY #Travis에 저장한 키 변수 사용
    bucket: taglog-build
    key: taglog.zip
    bundle-type: zip
    application: taglog
    deployment_group: taglog
    region: ap-northeast-2
    wait-until-deployed : true